image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:prod

.before_script_template:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-job:
  extends: .before_script_template
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE


#test:
#  stage: test
#  image: node:14
#  script:
#    - npm install
#    - npm run test
#    - npm run build
#  environment: development

release-image:
  extends: .before_script_template
  stage: release
  only:
    - main
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  environment: production

deploy_staging:
  stage: deploy
  dependencies:
    - build-job
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
  image: quay.io/openshift/origin-cli
  script:
    - wget https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    - export IMAGE=$CONTAINER_TEST_IMAGE
    - export COMMIT_ID=$CI_COMMIT_SHORT_SHA
    - export APP_NAME=ht-webdev-$CI_COMMIT_SHORT_SHA
    - export CONFIG_PATH=./config/k8s-dev/deployment.yaml
    - yq -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' CONFIG_PATH
    - yq -i '.metadata.name = strenv(APP_NAME)' CONFIG_PATH
    - yq -i '.spec.selector.matchLabels.deployment = strenv(APP_NAME)' CONFIG_PATH
    - yq -i '.spec.template.metadata.labels.deployment = strenv(APP_NAME)' CONFIG_PATH
    - yq -i '.spec.template.spec.containers[0].name = strenv(APP_NAME)' CONFIG_PATH
    - oc login --token=$OCP_TOKEN --server=$OCP_API_SERVER --insecure-skip-tls-verify
    - oc project ht-coop
    - RESULT=0
    - oc scale deployment -l app.kubernetes.io/instance=ht-web-dev --replicas=0 2> /dev/null || RESULT=$?
    - echo $RESULT
    - (if [ "$RESULT" == 1 ]; then
      exit 0;
      fi);
    - oc apply -f k8s-dev
  environment: development

deploy-prod:
  image: quay.io/openshift/origin-cli
  stage: deploy
  dependencies:
    - build-job
    - release-image
  only:
    - main
  script:
    - wget https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    - export IMAGE=$CONTAINER_RELEASE_IMAGE
    - export APP_NAME=ht-web-react
    - export CONFIG_PATH=./config/k8s/deployment.yaml
    - yq -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' CONFIG_PATH
    - yq -i '.metadata.name = strenv(APP_NAME)' CONFIG_PATH
    - yq -i '.spec.selector.matchLabels.deployment = strenv(APP_NAME)' CONFIG_PATH
    - yq -i '.spec.template.metadata.labels.deployment = strenv(APP_NAME)' CONFIG_PATH
    - yq -i '.spec.template.spec.containers[0].name = strenv(APP_NAME)' CONFIG_PATH
    - oc login --token=$OCP_TOKEN --server=$OCP_API_SERVER --insecure-skip-tls-verify
    - oc project ht-coop
    - RESULT=0
    - oc scale deployment -l app.kubernetes.io/instance=ht-website --replicas=0 2> /dev/null || RESULT=$?
    - echo $RESULT
    - (if [ "$RESULT" == 1 ]; then
      exit 0;
      fi);
    - oc apply -f k8s
  environment: development