apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: ht-bot-server
    app.kubernetes.io/component: ht-bot-server
    app.kubernetes.io/instance: ht-bot-server
  name: ht-bot-server
spec:
  ports:
    - name: 5005-tcp
      port: 5005
      protocol: TCP
      targetPort: 5005
  selector:
    app: ht-bot-server
  sessionAffinity: None
  type: ClusterIP
