apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: ht-web-dev
    app.kubernetes.io/component: ht-web-dev
    app.kubernetes.io/instance: ht-web-dev
  name: ht-web-dev
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: ht-web-dev
  sessionAffinity: None
  type: ClusterIP
